package goldenexport;

import board.BezierBoard;
import board.readers.BrdReader;

import java.io.File;
import java.io.PrintWriter;
import java.util.Locale;

/**
 * Golden-data exporter for the OpenShaper rebuild.
 *
 * Loads reference .brd files through the UNMODIFIED legacy kernel (board.BezierBoard +
 * board.readers.BrdReader, recompiled from ../../../boardcad-le/src via this project's
 * build.gradle) and emits the authoritative computed specs as JSON. The TypeScript
 * port in packages/kernel is then pinned to these values within stated tolerances.
 *
 * Usage:  gradle run --args="<golden-dir> <output-json>"
 *   <golden-dir>  directory containing shortboard.brd, funboard.brd, longboard.brd
 *   <output-json> file to write (e.g. ../../docs/specs/golden/golden.json)
 *
 * All length values are in the legacy internal unit: centimeters. Volume is cm^3,
 * area cm^2.
 */
public final class GoldenExporter {

    private static final String[] BOARDS = { "shortboard", "funboard", "longboard" };

    // Sample stations as fractions of length (nose=0 .. tail=1) for width/rocker/thickness.
    private static final double[] STATIONS = { 0.05, 0.25, 0.5, 0.75, 0.95 };

    public static void main(String[] args) throws Exception {
        if (args.length < 2) {
            System.err.println("usage: GoldenExporter <golden-dir> <output-json>");
            System.exit(2);
        }
        File dir = new File(args[0]);
        File out = new File(args[1]);

        StringBuilder json = new StringBuilder();
        json.append("{\n");
        json.append("  \"_comment\": \"Generated by GoldenExporter from the legacy BoardCAD-LE kernel. Units: cm, cm^2, cm^3.\",\n");
        json.append("  \"boards\": {\n");

        for (int b = 0; b < BOARDS.length; b++) {
            String name = BOARDS[b];
            File brd = new File(dir, name + ".brd");
            BezierBoard board = new BezierBoard();
            int rc = BrdReader.loadFile(board, brd.getAbsolutePath());
            if (rc != 0) {
                System.err.println("WARN: loadFile returned " + rc + " for " + brd + " (" + BrdReader.getErrorStr() + ")");
            }

            double length = board.getLength();
            json.append("    \"").append(name).append("\": {\n");
            appendNum(json, "length", length, ",");
            appendNum(json, "lengthOverCurve", board.getLengthOverCurve(), ",");
            appendNum(json, "maxWidth", board.getMaxWidth(), ",");
            appendNum(json, "maxWidthPos", board.getMaxWidthPos(), ",");
            appendNum(json, "centerWidth", board.getCenterWidth(), ",");
            appendNum(json, "thickness", board.getThickness(), ",");
            appendNum(json, "maxThickness", board.getMaxThickness(), ",");
            appendNum(json, "maxThicknessPos", board.getMaxThicknessPos(), ",");
            appendNum(json, "maxRocker", board.getMaxRocker(), ",");
            appendNum(json, "volume", board.getVolume(), ",");
            appendNum(json, "area", board.getArea(), ",");
            appendNum(json, "centerOfMass", board.getCenterOfMass(), ",");

            json.append("      \"stations\": [\n");
            for (int s = 0; s < STATIONS.length; s++) {
                double pos = STATIONS[s] * length;
                json.append("        { \"frac\": ").append(fmt(STATIONS[s]))
                    .append(", \"pos\": ").append(fmt(pos))
                    .append(", \"width\": ").append(fmt(board.getWidthAtPos(pos)))
                    .append(", \"rocker\": ").append(fmt(board.getRockerAtPos(pos)))
                    .append(", \"thickness\": ").append(fmt(board.getThicknessAtPos(pos)))
                    .append(" }").append(s < STATIONS.length - 1 ? "," : "").append("\n");
            }
            json.append("      ]\n");
            json.append("    }").append(b < BOARDS.length - 1 ? "," : "").append("\n");
        }

        json.append("  }\n}\n");

        out.getParentFile().mkdirs();
        try (PrintWriter w = new PrintWriter(out, "UTF-8")) {
            w.print(json);
        }
        System.out.println("Wrote golden data to " + out.getAbsolutePath());
    }

    private static void appendNum(StringBuilder sb, String key, double v, String trailing) {
        sb.append("      \"").append(key).append("\": ").append(fmt(v)).append(trailing).append("\n");
    }

    private static String fmt(double v) {
        if (Double.isNaN(v) || Double.isInfinite(v)) return "null";
        return String.format(Locale.US, "%.10g", v);
    }

    private GoldenExporter() {}
}
