package goldenexport;

import board.BezierBoard;
import board.readers.BrdReader;
import cadcore.AbstractBezierBoardSurfaceModel;
import cadcore.BezierBoardCrossSection;
import cadcore.BezierFit;
import cadcore.BezierKnot;
import cadcore.BezierSpline;

import java.awt.geom.Point2D;
import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Locale;

/**
 * Golden-data exporter for the three kernel correctness gaps (feat/kernel-interp):
 *
 *   1. sLinear cross-section area / volume
 *      (cadcore.BezierBoardSLinearInterpolationSurfaceModel.getCrosssectionAreaAt)
 *   2. Cross-section morph for differing control-point counts
 *      (cadcore.BezierBoardCrossSection.interpolate)
 *   3. BezierFit least-squares cubic fit
 *      (cadcore.BezierFit.bestFit)
 *
 * Runs the UNMODIFIED legacy kernel and writes JSON consumed by the TypeScript
 * port's golden tests. Units: cm, cm^2, cm^3.
 *
 * Usage:  gradle run --args="<golden-dir> <output-json>" -PmainClass=goldenexport.InterpGoldenExporter
 *   (or invoke main directly with the same two args)
 */
public final class InterpGoldenExporter {

    private static final String[] BOARDS = { "shortboard", "funboard", "longboard" };

    // x positions sampled as a fraction of board length for the sLinear area check.
    private static final double[] AREA_FRACS = { 0.1, 0.25, 0.5, 0.75, 0.9 };

    public static void main(String[] args) throws Exception {
        if (args.length < 2) {
            System.err.println("usage: InterpGoldenExporter <golden-dir> <output-json>");
            System.exit(2);
        }
        File dir = new File(args[0]);
        File out = new File(args[1]);

        StringBuilder json = new StringBuilder();
        json.append("{\n");
        json.append("  \"_comment\": \"Generated by InterpGoldenExporter from the legacy BoardCAD-LE kernel. Units: cm, cm^2, cm^3.\",\n");

        appendSLinear(json, dir);
        json.append(",\n");
        appendMorph(json);
        json.append(",\n");
        appendBezierFit(json);

        json.append("\n}\n");

        out.getParentFile().mkdirs();
        try (PrintWriter w = new PrintWriter(out, "UTF-8")) {
            w.print(json);
        }
        System.out.println("Wrote interp golden data to " + out.getAbsolutePath());
    }

    // --- Gap 1: sLinear area + volume -------------------------------------------------

    private static void appendSLinear(StringBuilder json, File dir) throws Exception {
        json.append("  \"sLinear\": {\n");
        for (int b = 0; b < BOARDS.length; b++) {
            String name = BOARDS[b];
            File brd = new File(dir, name + ".brd");
            BezierBoard board = new BezierBoard();
            BrdReader.loadFile(board, brd.getAbsolutePath());
            board.setInterpolationType(
                    AbstractBezierBoardSurfaceModel.ModelType.SLinearInterpolation);

            double length = board.getLength();
            json.append("    \"").append(name).append("\": {\n");
            json.append("      \"length\": ").append(fmt(length)).append(",\n");
            json.append("      \"volume\": ").append(fmt(board.getVolume())).append(",\n");
            json.append("      \"areas\": [\n");
            for (int s = 0; s < AREA_FRACS.length; s++) {
                double pos = AREA_FRACS[s] * length;
                // splits=10 matches the legacy VOLUME_X_SPLITS used by getVolume().
                double area = board.getCrossSectionAreaAt(pos, 10);
                json.append("        { \"frac\": ").append(fmt(AREA_FRACS[s]))
                    .append(", \"pos\": ").append(fmt(pos))
                    .append(", \"area\": ").append(fmt(area))
                    .append(" }").append(s < AREA_FRACS.length - 1 ? "," : "").append("\n");
            }
            json.append("      ]\n");
            json.append("    }").append(b < BOARDS.length - 1 ? "," : "").append("\n");
        }
        json.append("  }");
    }

    // --- Gap 2: cross-section morph (differing control-point counts) ------------------

    private static void appendMorph(StringBuilder json) {
        // Source: 4-knot section (3 inner-ish). Target: 3-knot section.
        // Coordinates are (x = half-width from centerline, y = height), legacy convention.
        BezierBoardCrossSection source = section(new double[][] {
            // end.x, end.y, prev.x, prev.y, next.x, next.y
            { 0.0, 0.0, -1.0, 0.0, 1.0, 0.0 },
            { 8.0, 0.3, 5.0, 0.0, 11.0, 0.6 },
            { 12.0, 3.0, 12.0, 1.5, 12.0, 4.5 },
            { 0.0, 6.0, 2.0, 6.0, -2.0, 6.0 },
        });
        BezierBoardCrossSection target = section(new double[][] {
            { 0.0, 0.0, -1.5, 0.0, 1.5, 0.0 },
            { 10.0, 2.5, 6.0, 0.5, 10.0, 4.5 },
            { 0.0, 5.0, 2.5, 5.0, -2.5, 5.0 },
        });

        json.append("  \"morph\": {\n");
        json.append("    \"sourceKnots\": ").append(knotsJson(source)).append(",\n");
        json.append("    \"targetKnots\": ").append(knotsJson(target)).append(",\n");
        json.append("    \"cases\": [\n");
        double[] ts = { 0.0, 0.25, 0.5, 0.75, 1.0 };
        for (int i = 0; i < ts.length; i++) {
            BezierBoardCrossSection result = source.interpolate(target, ts[i]);
            json.append("      { \"t\": ").append(fmt(ts[i]))
                .append(", \"knots\": ").append(knotsJson(result)).append(" }")
                .append(i < ts.length - 1 ? "," : "").append("\n");
        }
        json.append("    ]\n");
        json.append("  }");
    }

    private static BezierBoardCrossSection section(double[][] knots) {
        BezierSpline spline = new BezierSpline();
        for (double[] k : knots) {
            spline.append(new BezierKnot(k[0], k[1], k[2], k[3], k[4], k[5]));
        }
        BezierBoardCrossSection cs = new BezierBoardCrossSection();
        cs.setBezierSpline(spline);
        return cs;
    }

    private static String knotsJson(BezierBoardCrossSection cs) {
        BezierSpline spline = cs.getBezierSpline();
        StringBuilder sb = new StringBuilder("[");
        int n = spline.getNrOfControlPoints();
        for (int i = 0; i < n; i++) {
            BezierKnot k = spline.getControlPoint(i);
            Point2D.Double[] p = k.getPoints();
            sb.append("[")
              .append(fmt(p[0].x)).append(",").append(fmt(p[0].y)).append(",")
              .append(fmt(p[1].x)).append(",").append(fmt(p[1].y)).append(",")
              .append(fmt(p[2].x)).append(",").append(fmt(p[2].y))
              .append("]");
            if (i < n - 1) sb.append(",");
        }
        sb.append("]");
        return sb.toString();
    }

    // --- Gap 3: BezierFit -------------------------------------------------------------

    private static void appendBezierFit(StringBuilder json) {
        BezierFit fit = new BezierFit();

        json.append("  \"bezierFit\": {\n");
        json.append("    \"cases\": [\n");

        // Case A: points sampled along a known cubic (exact recovery expected to be loose,
        // since BezierFit uses chord-length param, not the true t).
        ArrayList<Point2D> a = new ArrayList<>();
        a.add(new Point2D.Double(0.0, 0.0));
        a.add(new Point2D.Double(1.0, 2.0));
        a.add(new Point2D.Double(2.0, 3.0));
        a.add(new Point2D.Double(3.0, 3.0));
        a.add(new Point2D.Double(4.0, 2.0));
        a.add(new Point2D.Double(5.0, 0.0));

        // Case B: a quarter-arc-like set of points.
        ArrayList<Point2D> bpts = new ArrayList<>();
        bpts.add(new Point2D.Double(0.0, 10.0));
        bpts.add(new Point2D.Double(2.0, 9.8));
        bpts.add(new Point2D.Double(5.0, 9.0));
        bpts.add(new Point2D.Double(8.0, 6.5));
        bpts.add(new Point2D.Double(9.8, 3.0));
        bpts.add(new Point2D.Double(10.0, 0.0));

        appendFitCase(json, fit, a, true);
        appendFitCase(json, fit, bpts, false);

        json.append("    ]\n");
        json.append("  }");
    }

    private static void appendFitCase(StringBuilder json, BezierFit fit,
            ArrayList<Point2D> points, boolean comma) {
        Point2D[] cp = fit.bestFit(points);
        json.append("      { \"points\": [");
        for (int i = 0; i < points.size(); i++) {
            Point2D p = points.get(i);
            json.append("[").append(fmt(p.getX())).append(",").append(fmt(p.getY())).append("]");
            if (i < points.size() - 1) json.append(",");
        }
        json.append("], \"controlPoints\": [");
        for (int i = 0; i < cp.length; i++) {
            json.append("[").append(fmt(cp[i].getX())).append(",").append(fmt(cp[i].getY())).append("]");
            if (i < cp.length - 1) json.append(",");
        }
        json.append("] }").append(comma ? "," : "").append("\n");
    }

    private static String fmt(double v) {
        if (Double.isNaN(v) || Double.isInfinite(v)) return "null";
        return String.format(Locale.US, "%.10g", v);
    }

    private InterpGoldenExporter() {}
}
